"""Compare unbounded and physical box-bounded exponential-decay fits.

Payoff: the bounded report ends with active bounds[1] marked lower.
"""

from nerai import Bounds, LeastSquaresProblem, ResidualModel, least_squares
from std.collections import List
from std.math import exp
from std.utils.numerics import inf


struct DecayResiduals(ResidualModel):
    def __init__(out self):
        pass

    def residual_count(self) -> Int:
        return 12

    def residuals(mut self, parameters: List[Float64]) raises -> List[Float64]:
        # Generated by scripts/generate_bounds_fixture.py (NumPy seed 11).
        var t = [
            0.0,
            0.36363636363636365,
            0.7272727272727273,
            1.0909090909090908,
            1.4545454545454546,
            1.8181818181818183,
            2.1818181818181817,
            2.5454545454545454,
            2.909090909090909,
            3.272727272727273,
            3.6363636363636367,
            4.0,
        ]
        var y = [
            0.5006838553450637,
            0.5417404053516538,
            0.5535853306626277,
            0.5334302221006102,
            0.5522224279596892,
            0.5621795888666042,
            0.5986672544241665,
            0.6006968930372695,
            0.6313013486887672,
            0.5939625949296087,
            0.676785520948536,
            0.6580713567968877,
        ]
        var result = List[Float64](length=12, fill=0.0)
        for index in range(12):
            result[index] = parameters[0] * exp(-parameters[1] * t[index]) - y[index]
        return result^


def main() raises:
    var unbounded_problem = LeastSquaresProblem(DecayResiduals(), [0.5, 0.1])
    var unbounded = least_squares(unbounded_problem)
    print("# Unbounded fit")
    print(unbounded, end="")
    print("# A negative rate means nonphysical exponential growth.")

    var bounds = Bounds(
        [0.0, 0.0],
        [inf[DType.float64](), inf[DType.float64]()],
    )
    var bounded_problem = LeastSquaresProblem(
        DecayResiduals(),
        [0.5, 0.1],
        bounds=bounds.copy(),
    )
    var bounded = least_squares(bounded_problem)
    print("# Bounded fit: amplitude and rate are non-negative")
    print(bounded, end="")
