"""Fit noisy exponential decay and print parameter standard errors.

Payoff: amplitude prints as 2.487 +/- 0.028 in the parameter report.
"""

from nerai import CurveFit, CurveModel
from std.collections import List
from std.math import exp


struct ExponentialDecay(CurveModel):
    def __init__(out self):
        pass

    def values(
        mut self, parameters: List[Float64], t: Span[Float64, ...]
    ) raises -> List[Float64]:
        var values = List[Float64](length=len(t), fill=0.0)
        for index in range(len(t)):
            values[index] = parameters[0] * exp(-parameters[1] * t[index])
        return values^


def main() raises:
    # Generated by scripts/generate_statistics_fixture.py (NumPy seed 42).
    var t = [
        0.0,
        0.20833333333333334,
        0.4166666666666667,
        0.625,
        0.8333333333333334,
        1.0416666666666667,
        1.25,
        1.4583333333333335,
        1.6666666666666667,
        1.875,
        2.0833333333333335,
        2.291666666666667,
        2.5,
        2.7083333333333335,
        2.916666666666667,
        3.125,
        3.3333333333333335,
        3.541666666666667,
        3.75,
        3.9583333333333335,
        4.166666666666667,
        4.375,
        4.583333333333334,
        4.791666666666667,
        5.0,
    ]
    var y = [
        2.5152358539877215,
        2.1087551483663853,
        1.9050663105664043,
        1.6611495518892907,
        1.2975361049924259,
        1.1406678953850795,
        1.0485470693546353,
        0.8849242942863328,
        0.7776680019112797,
        0.6302136754442806,
        0.6255290435363732,
        0.5415321783848346,
        0.43773639350417365,
        0.4318448652148168,
        0.34790590925119713,
        0.23752760315669744,
        0.26086745886513757,
        0.16158847170632618,
        0.22502190765099225,
        0.1540282248418524,
        0.126041297379791,
        0.08288007873970038,
        0.16218689287408977,
        0.07961970944963043,
        0.05407706744764089,
    ]
    var fit = CurveFit(ExponentialDecay(), t, y, [1.0, 1.0])

    print(fit.solve(), end="")
