"""Fit a Gaussian peak on a noisy synthetic spectrum.

Payoff: amplitude, center, and width arrive with +/- uncertainty estimates.
"""

from nerai import CurveFit, CurveModel
from std.collections import List
from std.math import exp


struct GaussianPeak(CurveModel):
    def __init__(out self):
        pass

    def values(
        mut self, parameters: List[Float64], x: Span[Float64, ...]
    ) raises -> List[Float64]:
        var values = List[Float64](length=len(x), fill=0.0)
        for index in range(len(x)):
            var normalized = (x[index] - parameters[1]) / parameters[2]
            values[index] = parameters[0] * exp(-0.5 * normalized * normalized)
        return values^


def main() raises:
    # Generated by scripts/generate_gaussian_fixture.py (NumPy seed 7).
    var x = [
        -5.0,
        -4.75,
        -4.5,
        -4.25,
        -4.0,
        -3.75,
        -3.5,
        -3.25,
        -3.0,
        -2.75,
        -2.5,
        -2.25,
        -2.0,
        -1.75,
        -1.5,
        -1.25,
        -1.0,
        -0.75,
        -0.5,
        -0.25,
        0.0,
        0.25,
        0.5,
        0.75,
        1.0,
        1.25,
        1.5,
        1.75,
        2.0,
        2.25,
        2.5,
        2.75,
        3.0,
        3.25,
        3.5,
        3.75,
        4.0,
        4.25,
        4.5,
        4.75,
        5.0,
    ]
    var y = [
        0.0001807352760405818,
        0.02410895173226558,
        -0.021421458399293176,
        -0.07005947188413682,
        -0.03372218389293266,
        -0.07366468868858532,
        0.016409248626213492,
        0.1299442519771425,
        0.003267852136104546,
        0.026980070024550495,
        0.1709981648850381,
        0.24568166840852007,
        0.35091841994889256,
        0.44282742810460207,
        0.7457164805348266,
        1.0914969278709645,
        1.265962921532036,
        1.707209792737026,
        1.967847014389081,
        2.3645696680131962,
        2.6032272641727485,
        2.916789885733709,
        2.898604281484504,
        2.9572983249254197,
        2.763106154126025,
        2.452778211625598,
        1.9186040567075076,
        1.7007236219525124,
        1.3696200096827569,
        1.044937391194566,
        0.6256457650914571,
        0.479044609598544,
        0.2642037537845295,
        0.15242372860166728,
        0.21668269074110857,
        0.012015287983594011,
        0.04004263722456927,
        0.09347822172343373,
        -0.03509027420104574,
        -0.0032691202556011075,
        0.011488610380763598,
    ]
    var fit = CurveFit(
        GaussianPeak(),
        x,
        y,
        [1.0, 0.0, 2.0],
        parameter_names=["amplitude", "center", "width"],
    )

    print(fit.solve(), end="")
